services:
  db:
    image: postgres:16
    container_name: bank-postgres
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bankpassword
      POSTGRES_DB: bank_db
    ports:
      - "5433:5432"
    volumes:
      - bank_pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10
    command: >
      -url=jdbc:postgresql://db:5432/bank_db
      -user=bank
      -password=bankpassword
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

volumes:
  bank_pgdata:
